services:
  # ------------------ Zookeeper ------------------
  zookeeper:
    image: bitnami/zookeeper:3
    platform: linux/amd64
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"


  # ------------------ Kafka ------------------
  kafka:
    image: bitnami/kafka:3
    platform: linux/amd64
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    ports:
      - "9092:9092"

  # ------------------ Flask API ------------------
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    environment:
     - SERVICE=flask
    ports:
      - "5000:5000"
    depends_on:
     - kafka
     - zookeeper

# ------------------ Kafka Producer ------------------
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer
    environment:
      - SERVICE=producer
      - KAFKA_BOOTSTRAP=kafka:9092
      - TOPIC=weather_stream
      - SLEEP_SEC=1
      - DATA_FILE=/app/data/master_data.csv
    volumes:
      - ./data:/app/data
    depends_on:
      - kafka
  # ------------------ Kafka Consumer ------------------
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer
    environment:
      - SERVICE=consumer
      - KAFKA_BOOTSTRAP=kafka:9092
      - TOPIC=weather_stream
      - GROUP_ID=weather-group
      - OUT_FILE=/app/data/stream/stream_data.csv
    volumes:
     - ./data:/app/data
    depends_on:
    - kafka
  # ------------------ Postgres for Airflow ------------------
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  # ------------------ Airflow Webserver ------------------
  airflow-webserver:
    image: apache/airflow:2.6.3
    container_name: airflow-webserver
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=airflow
      - _AIRFLOW_WWW_USER_PASSWORD=airflow
      - _AIRFLOW_WWW_USER_ROLE=Admin
      - _AIRFLOW_WWW_USER_EMAIL=admin@example.com
    volumes:
      - ./src/airflows:/opt/airflow/dags
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: webserver

  # ------------------ Airflow Scheduler ------------------
  airflow-scheduler:
    image: apache/airflow:2.6.3
    container_name: airflow-scheduler
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./src/airflows:/opt/airflow/dags
      - ./data:/opt/airflow/data
    command: scheduler

volumes:
  postgres-db-volume:
